"""Device provisioning primitives — shared between the MCP ``provision_device``
tool and the deferred ``reprovision`` recovery handler (factory-defaulted →
re-provision when it comes back).

Extracted from the MCP server so the API-process health loop can run the same
credential-creation logic the MCP tool uses (the MCP server runs as a separate
subprocess).

SECURITY: on a factory-defaulted device this writes **two** admin accounts —
``root`` with the operator-known fleet root password, then ADMZ's own ``admz``
account with a generated one — and stores only the ``admz`` password in the
registry; a root credential is never stored per device (FR-CRED-014,
ADR-0068). No password is ever returned, logged, or exposed; ADMZ uses the
stored one only to reach the device. The caller is responsible for
authorization (onboarding gates at the decision point, ADR-0059; the
unattended recovery handler is refused outright).
"""

from __future__ import annotations

import secrets
from typing import Any, Dict, Optional, Tuple

from admz.fleet_settings import fleet_settings


def generate_device_password(length: int = 24) -> str:
    """A strong random password with upper/lower/digit guaranteed."""
    while True:
        pw = secrets.token_urlsafe(length)[:length]
        if (any(c.isupper() for c in pw)
                and any(c.islower() for c in pw)
                and any(c.isdigit() for c in pw)):
            return pw


def serial_to_mac(serial: str) -> str:
    s = serial.upper().replace(":", "").replace("-", "")
    if len(s) != 12:
        return serial
    return ":".join(s[i:i + 2] for i in range(0, 12, 2))


async def execute_on_host(
    catalog: Any,
    executors: Any,
    host: str,
    operation_id: str,
    params: Dict[str, str],
    *,
    credentials: Optional[Dict[str, str]] = None,
    auth_method: str = "digest",
    auth: Optional[Dict[str, str]] = None,
    family: str = "vapix",
) -> Tuple[bool, Optional[str]]:
    """Run a VAPIX op against a bare host (no registered device). Returns
    ``(ok, error)``."""
    operation = catalog.get_operation(family, operation_id)
    if not operation:
        return False, f"Operation '{operation_id}' not found in {family} catalog"

    executor = executors.get(family)
    if not executor:
        return False, f"No executor for family '{family}'"

    device: Dict[str, Any] = {
        "host": host,
        "device_id": f"_host_{host}",
        "auth_method": auth_method,
        "port": 80,
    }
    if auth:
        device["auth"] = auth
    else:
        device["auth"] = {"http": auth_method, "https": auth_method, "scheme": "http"}

    creds = credentials or {"username": "", "password": ""}
    op_dict = {
        "id": operation.id,
        "cgi": operation.cgi,
        "method": operation.method,
        "risk_level": operation.risk_level,
        "request": operation.request,
        "response": operation.response,
        "requires": operation.requires,
        "_endpoint": operation.endpoint,
        "_generation": operation.generation,
        "_auth": operation.auth,
        "service_impact": operation.service_impact,
        "base_path": operation.base_path,
        "path": operation.path,
    }
    result = await executor.execute(op_dict, device, creds, params)
    if result.success:
        return True, None
    return False, result.error or f"HTTP {result.status_code}"


def store_provisioned_creds(
    registry: Any, device_id: str, username: str, password: str,
    purpose: str = "Provisioned by provision_device",
    *,
    generated_by_admz: bool = False,
) -> None:
    """Store the provisioned admin credential as the device's ``default``
    account (replacing any existing one).

    ``generated_by_admz`` records PROVENANCE: this password was generated by
    ADMZ and exists nowhere else. ADR-0068 uses it to decide whether ADMZ may
    rotate the credential it authenticated with — it may rotate its own
    generated value, and never one a human supplied. Absent means
    human-supplied, so the conservative branch is the default for every row
    written before this existed.
    """
    account_data = {
        "username": username,
        "password": password,
        "account_type": "admin",
        "purpose": purpose,
        "generated_by_admz": generated_by_admz,
    }
    if registry.account_exists(device_id, "default"):
        registry.remove_account(device_id, "default")
    registry.add_account(device_id, "default", account_data)


#: The account ADMZ creates for its own ongoing use (ADR-0061, FR-CRED-011).
OWN_ACCOUNT_USERNAME = "admz"

#: The fleet-wide root password ADMZ writes to a device it provisions
#: (ADR-0068, FR-CRED-014).
#:
#: **Break-glass, and deliberately not per-device.** The operator knows this
#: value, so every device ADMZ provisioned stays reachable by hand after
#: ADMZ's database is lost — which is precisely the cost FR-CRED-007 used to
#: document and accept ("it is factory-reset and provisioned again"). It is
#: store-encrypted and never LLM-writable; see ``admz/setting_policy.py``.
#:
#: This is the ONLY fleet setting this module reads, and
#: ``tests/test_provisioning.py`` pins that both ways: the fleet
#: ``default_password`` is an *entry* credential and must never reach a device.
FLEET_ROOT_PASSWORD_KEY = "fleet_root_password"


async def adopt_with_admz_account(
    catalog: Any,
    executors: Any,
    registry: Any,
    *,
    device_id: str,
    host: str,
    entry: Dict[str, str],
    device_info: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Use a working entry credential to create ADMZ's own account.

    ADR-0061: fleet credentials get ADMZ **in**; the per-device ``admz`` account
    keeps it in. This is the second half — the caller has already proved
    ``entry`` authenticates, and this converts that one-time access into a
    credential nothing else holds.

    Differs from :func:`provision_factory_default` in the one way that matters:
    that function writes to a device with **no** account and therefore uses
    ``auth_method="none"``. This one authenticates *as* the entry credential,
    because the device is already set up.

    **The entry credential is never removed or rotated.** If ADMZ's database is
    lost, every generated password goes with it and the entry credential is the
    only way back in. That is a rule, not a preference — see ADR-0061.

    Returns a result dict; the generated password is never in it.
    """
    new_password = generate_device_password()
    ok, error = await execute_on_host(
        catalog, executors, host, "pwdgrp.cgi:add-user",
        params={
            "username": OWN_ACCOUNT_USERNAME,
            "password": new_password,
            "group": "root",
            "secondary_groups": "admin:operator:viewer:ptz",
        },
        credentials=entry,
        auth_method=(device_info or {}).get("auth_method") or "digest",
        auth=(device_info or {}).get("auth"),
    )
    if not ok:
        # The entry credential still works even though this did not, but the
        # caller must NOT fall back to storing it: ADR-0068 retired that
        # fallback. Nothing is stored, and the credential that got ADMZ in
        # stays the way back.
        return {"success": False, "status": "admz_account_failed",
                "device_id": device_id, "error": error}

    store_provisioned_creds(
        registry, device_id, OWN_ACCOUNT_USERNAME, new_password,
        purpose="ADMZ's own account, created at adoption (ADR-0061)",
        generated_by_admz=True,
    )
    return {"success": True, "status": "admz_account_created",
            "device_id": device_id, "username": OWN_ACCOUNT_USERNAME}


async def write_root_account(
    catalog: Any,
    executors: Any,
    *,
    host: str,
    password: str,
    username: str = "root",
) -> Tuple[bool, Optional[str]]:
    """Create the FIRST admin account on a factory-default device.

    **Takes no ``registry``, and that is the entire point** (ADR-0068). "This
    function cannot store a credential" is a property of the signature,
    checkable without reading the body — rather than a ``persist=False``
    boolean a future caller can get wrong. A root credential is never stored
    per device, so the write and the store are different functions.

    ``auth_method="none"``: by definition of ``needsetup=yes`` the device has
    no account to authenticate as yet.

    Returns ``(ok, error)``; the password is never returned or logged.
    """
    return await execute_on_host(
        catalog, executors, host, "pwdgrp.cgi:add-user",
        params={
            "username": username,
            "password": password,
            "group": "root",
            "secondary_groups": "admin:operator:viewer:ptz",
        },
        auth_method="none",
    )


async def rotate_root_to_break_glass(
    catalog: Any,
    executors: Any,
    *,
    host: str,
    entry: Dict[str, str],
    device_info: Optional[Dict[str, Any]] = None,
) -> Tuple[Optional[bool], Optional[str]]:
    """Reset ``entry``'s account to the fleet break-glass password.

    ADR-0068 §8, and the one place ADMZ rotates a credential it came in on.
    ADR-0061 forbade that outright, for a stated reason — a lost database made
    every generated password unrecoverable — and the break-glass value removes
    exactly that reason. So the rule narrows rather than disappears: ADMZ may
    rotate a password **it generated itself**, never one a human supplied.
    The caller checks provenance; this function only performs the write.

    Returns ``(None, reason)`` when there is nothing to rotate to — an unset
    break-glass password is not a failure, it just means the old value stays.
    """
    break_glass = fleet_settings.get(FLEET_ROOT_PASSWORD_KEY)
    if not break_glass:
        return None, f"{FLEET_ROOT_PASSWORD_KEY} is not configured"
    ok, error = await execute_on_host(
        catalog, executors, host, "pwdgrp.cgi:update-user",
        params={"username": entry["username"], "password": break_glass},
        credentials=entry,
        auth_method=(device_info or {}).get("auth_method") or "digest",
        auth=(device_info or {}).get("auth"),
    )
    return ok, error


async def provision_factory_default(
    catalog: Any,
    executors: Any,
    registry: Any,
    *,
    device_id: str,
    host: str,
    username: str = "root",
    password: Optional[str] = None,
    attended: bool = True,
) -> Dict[str, Any]:
    """Provision a FACTORY-DEFAULT device with **two** accounts (ADR-0068).

    ``root`` from the fleet break-glass password, then ADMZ's own ``admz``
    account with a generated one — and **only ``admz`` is stored**. A root
    credential is never stored per device.

    The order is fixed and the reason is the owner's: *"I don't want the admz
    generated password to be the only credential on the device."* Root is
    therefore a deliberate second credential a human knows, which is what lets
    an operator back into a provisioned device after ADMZ's database is lost.
    That deletes the trade FR-CRED-007 used to accept — factory-reset and
    provision again — and it is why the ``admz``-on-factory-default question
    (ADR-0064 decision 9) is now **moot** rather than deferred: root is written
    first either way, so whether an Axis unit would accept a non-``root`` first
    account no longer gates anything.

    Two refusals, both writing nothing:

    - **``attended=False``** — the deferred ``reprovision`` handler fires up to
      24h later, unattended, against whatever host answers at the device's
      registered address at that moment. ``needsetup=yes`` is itself an
      unauthenticated claim and nothing on that path re-verifies the peer
      (#185/#326), so a spoofed peer would walk away with a credential valid on
      every device ADMZ provisioned. ADR-0068 requires that path to defer to an
      attended flow instead — which ``tasks/handlers.py`` already named as the
      honest fix. This replaces the old ``allow_fleet_default=False``: that flag
      is gone, and without an explicit refusal here removing it would have made
      the unattended handler silently START sending the shared value.
    - **No break-glass password configured** — the only alternatives are storing
      root (forbidden) or generating-and-discarding it (a device nobody can ever
      log into, which is worse than today). So refusing is the only consistent
      answer, and an operator setting one key is the prerequisite.

    ADR-0068 states the exposure this knowingly reinstates rather than claiming
    per-device non-storage mitigates it: it does not — the wire exposure is
    unchanged. What changes is that the disclosed value unlocks no device's
    ``admz`` account, and that recovery is rotating one setting.

    ``password`` still overrides the setting, for a caller that has its own.
    Returns a result dict; no password is ever in it.
    """
    if not attended:
        return {"success": False, "status": "unattended_not_permitted",
                "device_id": device_id,
                "error": ("provisioning writes the fleet root password and "
                          "may only run attended (ADR-0068); "
                          "this device needs an operator-driven onboard")}

    root_password = password or fleet_settings.get(FLEET_ROOT_PASSWORD_KEY)
    if not root_password:
        return {"success": False, "status": "root_password_not_configured",
                "device_id": device_id,
                "error": (f"no fleet root password is set ({FLEET_ROOT_PASSWORD_KEY}); "
                          "ADMZ will not provision a device it cannot leave a "
                          "known credential on")}
    root_source = "provided" if password else "fleet_root"

    ok, error = await write_root_account(
        catalog, executors, host=host, password=root_password, username=username,
    )
    if not ok:
        # Nothing was written and nothing is stored: the write is what failed.
        return {"success": False, "status": "vapix_error", "stage": "root",
                "device_id": device_id, "error": error}

    # The device now requires auth. Recorded before the second write so a
    # crash between them still leaves the profile truthful.
    try:
        registry.update_device_info(device_id, {"auth_method": "digest"})
    except Exception:  # noqa: BLE001 - best effort
        pass

    adopted = await adopt_with_admz_account(
        catalog, executors, registry,
        device_id=device_id, host=host,
        entry={"username": username, "password": root_password},
        device_info={"auth_method": "digest"},
    )
    if not adopted.get("success"):
        # STORE NOTHING (ADR-0068 decision 4). Root is set to a password the
        # operator knows, so the device is recoverable by hand; storing the
        # break-glass value per device to paper over this is the one thing the
        # invariant forbids. The device reads `no_credentials`, which is the
        # honest projection of what happened.
        return {"success": False, "status": "admz_account_failed",
                "device_id": device_id, "root_set": True,
                "root_username": username, "root_password_source": root_source,
                "error": adopted.get("error")}

    return {"success": True, "status": "provisioned", "device_id": device_id,
            "username": OWN_ACCOUNT_USERNAME, "root_username": username,
            "root_password_source": root_source, "password_source": "generated"}
