id: snmp.cgi:setConfiguration
cgi: snmp.cgi

method: PATCH
base_path: /config/rest/snmp/v1
path: /

request:
  content_type: application/json

response:
  format: json

risk_level: normal

requires:
  auth_level: admin
