id: network_settings.cgi:setGlobalProxyConfiguration
cgi: network_settings.cgi

method: POST
min_api_version: "1.0"

request:
  content_type: application/json
  body:
    apiVersion: "1.0"
    method: setGlobalProxyConfiguration
    params:
      httpProxyHost: "{httpProxyHost}"
      httpProxyPort: "{httpProxyPort:int}"
      httpsProxyHost: "{httpsProxyHost}"
      httpsProxyPort: "{httpsProxyPort:int}"

response:
  format: json
  data_path: data

risk_level: normal

requires:
  auth_level: admin
